### ISSUE TITLE
On phosh, no way to close the preferences dialog

### ISSUE THREAD

**Issue by azmeuk** [dialect-app/dialect#255]
On a Librem5 with the phosh compositor, there is no way to close the dialect preferences dialog.

I am not sure whose responsibility it is though.

![dialect](https://user-images.githubusercontent.com/60163/170329876-ed0b7258-ae83-4a9f-bd79-0f7e76b41e02.png)

**Comment by fushinari** [comment]
Should be fixed with the new release.

**Comment by azmeuk** [comment]
Hi. I just installed 2.0.1 with flatpak, and this issue is still valid
![2022-07-17-182435](https://user-images.githubusercontent.com/60163/179411507-a21b2de7-e1c8-4137-a3cb-ba36d4a1c632.png)
.

**Comment by rafaelmardojai** [comment]
@azmeuk the window fits well, so I will say that the compositor isn't maximizing the window for some reason.

**Comment by azmeuk** [comment]
The lack of vertical maximizing is one thing, but I can live with that. However the issue reported in this ticket was that there is no way to close the preference window.

**Comment by rafaelmardojai** [comment]
So definitely a  `phosh` or `libadwaita` issue. We only construct a `AdwPreferencesWindow`, so we don't touch the headerbar. Maybe your compositor is removing the button because the window has the `modal` property se  to `true`.

Could you verify if other apps using `AdwPreferencesWindow` have the same issue?
